import { supabase } from '@/lib/supabase';

export interface CoachConfig {
  name: string;
  system_prompt: string;
  method: string;
  icon_name: string;
  color: string;
  tagline?: string;
  description?: string;
}

export interface ShareLinkResponse {
  shareId: string;
  deepLink: string;
  webUrl: string;
}

export interface ResolvedCoachShare {
  coachConfig: CoachConfig;
  creatorId: string;
}

/**
 * Get the base URL for functions
 */
function getFunctionsBaseUrl(): string {
  const explicit = process.env.EXPO_PUBLIC_SUPABASE_FUNCTIONS_URL;
  if (explicit) {
    const normalized = explicit.replace(/\/$/, '');
    if (normalized.includes('/functions/v1')) {
      return normalized;
    }
    return `${normalized}/functions/v1`;
  }

  const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL;
  if (!supabaseUrl) {
    throw new Error('Missing EXPO_PUBLIC_SUPABASE_URL');
  }

  return `${supabaseUrl.replace(/\/$/, '')}/functions/v1`;
}

/**
 * Get authorization header for API calls
 */
async function getAuthHeader(): Promise<string> {
  const { data } = await supabase.auth.getSession();
  const token = data.session?.access_token;
  if (!token) {
    throw new Error('Missing Supabase access token');
  }

  return `Bearer ${token}`;
}

/**
 * Create a shareable link for a coach
 * @param coachId - The ID of the coach to share
 * @param coachConfig - The coach configuration to include in the share
 * @returns ShareLinkResponse with deepLink and webUrl
 */
export async function createShareLink(
  coachId: string,
  coachConfig: CoachConfig
): Promise<ShareLinkResponse> {
  try {
    const authHeader = await getAuthHeader();
    const functionsUrl = getFunctionsBaseUrl();

    const response = await fetch(`${functionsUrl}/coach-share`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: authHeader,
      },
      body: JSON.stringify({
        action: 'create',
        coach_id: coachId,
        coach_config: coachConfig,
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Failed to create share link: ${error}`);
    }

    const data = await response.json();

    return {
      shareId: data.share_id,
      deepLink: data.share_url, // Already in format: coachgenie://coach/share/{share_id}
      webUrl: `https://coachgenie.app/share/${data.share_id}`,
    };
  } catch (error) {
    console.error('Error creating share link:', error);
    throw error;
  }
}

/**
 * Resolve a shared coach link and get the coach configuration
 * @param shareId - The share ID to resolve
 * @returns ResolvedCoachShare with coach config and creator info
 */
export async function resolveShareLink(
  shareId: string
): Promise<ResolvedCoachShare> {
  try {
    const authHeader = await getAuthHeader();
    const functionsUrl = getFunctionsBaseUrl();

    const response = await fetch(`${functionsUrl}/coach-share`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: authHeader,
      },
      body: JSON.stringify({
        action: 'resolve',
        share_id: shareId,
      }),
    });

    if (!response.ok) {
      if (response.status === 404) {
        throw new Error('Share link not found or has expired');
      }
      const error = await response.text();
      throw new Error(`Failed to resolve share link: ${error}`);
    }

    const data = await response.json();

    return {
      coachConfig: data.coach_config,
      creatorId: data.creator_id,
    };
  } catch (error) {
    console.error('Error resolving share link:', error);
    throw error;
  }
}

/**
 * Import a shared coach into the user's coaches
 * @param shareId - The share ID to import
 * @param coachId - Optional: custom coach ID. If not provided, one will be generated
 * @returns The created coach data
 */
export async function importSharedCoach(
  shareId: string,
  coachId?: string
): Promise<{ id: string; name: string; icon_name: string; color: string }> {
  try {
    // First resolve the share to get the coach config
    const resolved = await resolveShareLink(shareId);

    // Keep API compatibility for callers passing coachId, but DB id is generated by schema.
    void coachId;
    const slugBase = resolved.coachConfig.name
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .slice(0, 50);
    const slug = `${slugBase || 'shared-coach'}-${Date.now().toString(36)}`;

    // Get the authenticated user
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      throw new Error('User not authenticated');
    }

    // Create the coach in the user's coaches table
    const { data: coach, error } = await supabase
      .from('coaches')
      .insert({
        user_id: user.id,
        created_by: user.id,
        slug,
        name: resolved.coachConfig.name,
        tagline: resolved.coachConfig.tagline ?? '',
        description: resolved.coachConfig.description ?? '',
        icon_name: resolved.coachConfig.icon_name,
        color: resolved.coachConfig.color,
        method: resolved.coachConfig.method,
        system_prompt: resolved.coachConfig.system_prompt,
        version: '1.0.0',
        is_public: false,
        created_at: new Date().toISOString(),
      })
      .select('id, name, icon_name, color')
      .single();

    if (error) {
      throw new Error(`Failed to import coach: ${error.message}`);
    }

    if (!coach) {
      throw new Error('Failed to create coach record');
    }

    return {
      id: coach.id,
      name: coach.name,
      icon_name: coach.icon_name ?? 'sparkles',
      color: coach.color ?? '#C5A059',
    };
  } catch (error) {
    console.error('Error importing shared coach:', error);
    throw error;
  }
}

/**
 * Validate a share ID format
 * @param shareId - The share ID to validate
 * @returns true if valid format, false otherwise
 */
export function isValidShareId(shareId: string): boolean {
  // Share IDs are 8 alphanumeric characters
  return /^[a-zA-Z0-9]{8}$/.test(shareId);
}
